import {
  pathaoRoutingFailureKey,
  resolvePathaoRouting,
  type PathaoRoutingFailure,
} from '@/lib/courier/pathao-routing';
import { getCourierProvider, isCourierProviderId } from '@/lib/courier/providers';
import {
  configuredProviders,
  getCourierIntegrationSettings,
  type CourierIntegrationDoc,
} from '@/lib/courier/settings';
import {
  CourierApiError,
  type CourierDispatchInput,
  type CourierProviderId,
  type CourierStatus,
} from '@/lib/courier/types';
import createLogger from '@/lib/logger';
import Courier from '@/lib/models/Courier';
import Order from '@/lib/models/Order';
import connectDB from '@/lib/mongodb';
import { notifyCustomerOrderStatusChanged } from '@/lib/notifications/events';

/**
 * Turning a local `Courier` record into a real consignment at Pathao or
 * Steadfast, and keeping its status in step afterwards.
 *
 * Every entry point here is idempotent on `consignmentId`: a courier that
 * already has one is never dispatched twice, so a retried queue job, a
 * double-clicked button and a replayed webhook are all free.
 */

const logger = createLogger('courier-dispatch');

export interface DispatchOutcome {
  courierId: string;
  orderNumber?: string;
  ok: boolean;
  /** True when the courier already had a consignment and was left alone. */
  skipped?: boolean;
  provider?: CourierProviderId;
  consignmentId?: string;
  trackingCode?: string;
  error?: string;
}

/** Builds the provider-neutral payload from a stored courier record. */
function toDispatchInput(courier: any, orderNumber: string): CourierDispatchInput {
  return {
    merchantOrderId: courier.merchantOrderId || orderNumber || courier.courierId,
    recipientName: courier.receiver?.name ?? '',
    recipientPhone: courier.receiver?.phone ?? '',
    recipientAddress: [
      courier.receiver?.address,
      courier.receiver?.city,
      courier.receiver?.district,
    ]
      .filter(Boolean)
      .join(', '),
    recipientCityName: courier.receiver?.city,
    recipientZoneName: courier.receiver?.district,
    itemQuantity: courier.parcel?.quantity ?? 1,
    itemWeight: courier.parcel?.weight ?? 0.5,
    itemDescription: courier.parcel?.description ?? 'Order items',
    // The note reaches the rider, so the bookkeeping line the confirmation
    // hook writes ("Auto-generated from order …") is left out — only a note
    // someone actually wrote is worth sending.
    specialInstruction: isAutoGeneratedNote(courier.notes)
      ? undefined
      : courier.notes || undefined,
    amountToCollect: courier.isCOD ? (courier.codAmount ?? 0) : 0,
    pathaoCityId: courier.providerMeta?.pathaoCityId,
    pathaoZoneId: courier.providerMeta?.pathaoZoneId,
    pathaoAreaId: courier.providerMeta?.pathaoAreaId,
    pathaoStoreId: courier.providerMeta?.pathaoStoreId || undefined,
  };
}

/** Matches the boilerplate both order-confirmation hooks write. */
function isAutoGeneratedNote(note: unknown): boolean {
  return typeof note === 'string' && /^Auto-generated from order\b/i.test(note.trim());
}

/** Fails fast on the fields both providers reject, before spending a call. */
export function validateDispatchInput(input: CourierDispatchInput): string | null {
  if (!input.recipientName.trim()) return 'Recipient name is missing.';
  if (!input.recipientPhone.trim()) return 'Recipient phone is missing.';
  if (input.recipientAddress.trim().length < 10) {
    return 'Recipient address is too short — both providers require at least 10 characters.';
  }
  return null;
}

/**
 * A routing failure as a sentence for `dispatchError`.
 *
 * `dispatchError` is a free-text column read back by whichever admin opens the
 * failed lane, so the row also carries `routingErrorKey` for the UI to localise.
 * This string is the fallback for anything reading the record directly — a log,
 * an export, an API consumer.
 */
function describeRoutingFailure(reason: PathaoRoutingFailure, detail?: string): string {
  const suffix = detail ? ` (${detail})` : '';
  switch (reason) {
    case 'pathao-not-configured':
      return 'Pathao is not enabled or its credentials are incomplete.';
    case 'no-district':
      return 'The shipping address has no district, which Pathao needs to route the parcel.';
    case 'city-unresolved':
      return `No Pathao city matches this district${suffix}. Set the routing manually and retry.`;
    case 'zone-unresolved':
      return `No Pathao zone matches this address${suffix}. Set the routing manually and retry.`;
    case 'lookup-failed':
      return `Could not reach Pathao to resolve the address${suffix}.`;
  }
}

/**
 * Dispatches one courier record.
 *
 * `provider` overrides the courier's own `courierPartner`, which in turn
 * overrides the configured default — so a bulk dispatch can force a partner
 * without rewriting each record first.
 */
export async function dispatchCourier(
  courierId: string,
  options: {
    provider?: CourierProviderId;
    settings?: CourierIntegrationDoc;
    /** Re-send even if a consignment already exists (admin-initiated only). */
    force?: boolean;
  } = {},
): Promise<DispatchOutcome> {
  await connectDB();

  const courier = await Courier.findById(courierId).populate('order', 'orderNumber');
  if (!courier) {
    return { courierId, ok: false, error: 'Courier record not found.' };
  }

  const orderNumber = (courier.order as any)?.orderNumber ?? '';

  if (courier.consignmentId && !options.force) {
    return {
      courierId,
      orderNumber,
      ok: true,
      skipped: true,
      provider: isCourierProviderId(courier.courierPartner)
        ? courier.courierPartner
        : undefined,
      consignmentId: courier.consignmentId,
      trackingCode: courier.trackingCode,
    };
  }

  const settings = options.settings ?? (await getCourierIntegrationSettings());
  const providerId =
    options.provider ??
    (isCourierProviderId(courier.courierPartner) ? courier.courierPartner : undefined) ??
    settings.defaultProvider;

  if (!isCourierProviderId(providerId)) {
    return { courierId, orderNumber, ok: false, error: 'No courier provider selected.' };
  }
  if (!configuredProviders(settings).includes(providerId)) {
    return {
      courierId,
      orderNumber,
      ok: false,
      provider: providerId,
      error: `${providerId} is not enabled or its credentials are incomplete.`,
    };
  }

  // Stamped before the call so the provider's webhook can find this record
  // even if our own response handling fails afterwards.
  if (!courier.merchantOrderId) {
    courier.merchantOrderId = orderNumber || courier.courierId;
  }

  const input = toDispatchInput(courier, orderNumber);
  const invalid = validateDispatchInput(input);
  if (invalid) {
    courier.dispatchError = invalid;
    await courier.save();
    return { courierId, orderNumber, ok: false, provider: providerId, error: invalid };
  }

  /*
   * Pathao routing.
   *
   * Pathao cannot take an address as text: `recipient_city` and
   * `recipient_zone` are required integers. The adapter used to omit them when
   * unresolved, on the belief that Pathao would infer the routing from the
   * address — it does not, it returns a validation error, and since nothing in
   * the codebase ever wrote `providerMeta` they were unresolved on every single
   * auto-created record. Pathao auto-dispatch could not have worked.
   *
   * Resolved once and stored, so a retry does not repeat the lookup and an
   * admin can see which city and zone the parcel was booked against.
   */
  if (providerId === 'pathao' && !courier.providerMeta?.pathaoCityId) {
    const resolved = await resolvePathaoRouting(
      {
        district: courier.receiver?.district,
        city: courier.receiver?.city,
        division: courier.receiver?.division,
        street: courier.receiver?.address,
      },
      { settings },
    );

    if (!resolved.ok) {
      // Never book blind. An unresolvable address parks the consignment in the
      // failed lane with the reason attached, where an admin can set the
      // routing by hand and retry — silently dropping it, or sending it with
      // missing fields and letting Pathao reject it, both lose the parcel.
      const error = describeRoutingFailure(resolved.reason, resolved.detail);
      courier.dispatchError = error;
      courier.routingErrorKey = pathaoRoutingFailureKey(resolved.reason);
      await courier.save();
      return { courierId, orderNumber, ok: false, provider: providerId, error };
    }

    courier.providerMeta = {
      ...(courier.providerMeta ?? {}),
      pathaoCityId: resolved.routing.cityId,
      pathaoZoneId: resolved.routing.zoneId,
      pathaoAreaId: resolved.routing.areaId,
    };
    courier.routingErrorKey = undefined;
    input.pathaoCityId = resolved.routing.cityId;
    input.pathaoZoneId = resolved.routing.zoneId;
    input.pathaoAreaId = resolved.routing.areaId;
  }

  try {
    const provider = await getCourierProvider(providerId, settings);
    const result = await provider.createConsignment(input);

    courier.courierPartner = providerId;
    courier.consignmentId = result.consignmentId;
    courier.trackingCode = result.trackingCode;
    // Steadfast's tracking code is the customer-facing number; Pathao has none,
    // so the consignment id doubles as it.
    courier.trackingNumber = result.trackingCode || result.consignmentId;
    courier.providerStatus = result.providerStatus;
    courier.providerDeliveryFee = result.deliveryFee;
    courier.dispatchedAt = new Date();
    courier.lastSyncedAt = new Date();
    courier.dispatchError = undefined;
    if (result.status && result.status !== courier.status) {
      courier.status = result.status;
    }
    courier.statusHistory.push({
      status: courier.status,
      timestamp: new Date(),
      notes: `Dispatched to ${providerId} (consignment ${result.consignmentId})`,
    });
    await courier.save();

    await mirrorToOrder(courier);

    logger.info('Courier dispatched', {
      courierId: courier.courierId,
      provider: providerId,
      consignmentId: result.consignmentId,
    });

    return {
      courierId,
      orderNumber,
      ok: true,
      provider: providerId,
      consignmentId: result.consignmentId,
      trackingCode: result.trackingCode,
    };
  } catch (error) {
    const message =
      error instanceof CourierApiError
        ? error.message
        : error instanceof Error
          ? error.message
          : 'Dispatch failed';
    courier.dispatchError = message;
    await courier.save();
    logger.error('Courier dispatch failed', {
      courierId: courier.courierId,
      provider: providerId,
      error: message,
    });
    return { courierId, orderNumber, ok: false, provider: providerId, error: message };
  }
}

/** Sequential on purpose: both providers rate-limit, and a bulk run is small. */
export async function dispatchCouriers(
  courierIds: string[],
  options: { provider?: CourierProviderId; force?: boolean } = {},
): Promise<DispatchOutcome[]> {
  const settings = await getCourierIntegrationSettings();
  const outcomes: DispatchOutcome[] = [];
  for (const id of courierIds) {
    outcomes.push(await dispatchCourier(id, { ...options, settings }));
  }
  return outcomes;
}

/**
 * Dispatches the courier attached to an order, if the admin asked for that to
 * happen automatically on confirmation.
 *
 * Never throws: a courier problem must not roll back the order status change
 * that triggered it — the same rule the notification dispatcher follows.
 */
export async function autoDispatchOrderCourier(orderId: string): Promise<void> {
  try {
    const settings = await getCourierIntegrationSettings();
    if (!settings.autoDispatchOnConfirm) return;

    const courier = await Courier.findOne({ order: orderId }).select('_id consignmentId');
    if (!courier || courier.consignmentId) return;

    await dispatchCourier(courier._id.toString(), { settings });
  } catch (error) {
    logger.error('Auto-dispatch on order confirmation failed', {
      orderId,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}

/** Pulls the current status from the provider and applies it locally. */
export async function syncCourierStatus(
  courierId: string,
  settings?: CourierIntegrationDoc,
): Promise<{ ok: boolean; status?: CourierStatus; providerStatus?: string; error?: string }> {
  await connectDB();

  const courier = await Courier.findById(courierId);
  if (!courier) return { ok: false, error: 'Courier record not found.' };
  if (!courier.consignmentId) {
    return { ok: false, error: 'Courier has not been dispatched yet.' };
  }
  if (!isCourierProviderId(courier.courierPartner)) {
    return { ok: false, error: 'Courier is not attached to an integrated provider.' };
  }

  try {
    const provider = await getCourierProvider(
      courier.courierPartner,
      settings ?? (await getCourierIntegrationSettings()),
    );
    const result = await provider.fetchStatus({
      consignmentId: courier.consignmentId,
      trackingCode: courier.trackingCode,
      merchantOrderId: courier.merchantOrderId,
    });

    if (!result) {
      courier.lastSyncedAt = new Date();
      await courier.save();
      return { ok: false, error: 'The provider returned no status for this consignment.' };
    }

    await applyProviderStatus(courier, result.providerStatus, result.status, 'sync');
    return { ok: true, status: courier.status, providerStatus: result.providerStatus };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Status sync failed';
    logger.error('Courier status sync failed', { courierId: courier.courierId, error: message });
    return { ok: false, error: message };
  }
}

export async function syncCourierStatuses(courierIds: string[]) {
  const settings = await getCourierIntegrationSettings();
  const results: Array<{ courierId: string; ok: boolean; status?: string; error?: string }> = [];
  for (const id of courierIds) {
    const result = await syncCourierStatus(id, settings);
    results.push({ courierId: id, ...result });
  }
  return results;
}

/**
 * Writes a provider status onto a courier record and mirrors it to the order.
 *
 * Shared by the sync route and both webhook handlers, so a status arriving by
 * push and one we polled for are handled identically. An unmapped provider
 * status is recorded verbatim but leaves our own status alone, rather than
 * guessing at a state machine we do not control.
 */
export async function applyProviderStatus(
  courier: any,
  providerStatus: string,
  mapped: CourierStatus | null,
  source: 'sync' | 'webhook',
): Promise<void> {
  const previousStatus = courier.status;
  courier.providerStatus = providerStatus;
  courier.lastSyncedAt = new Date();

  if (mapped && mapped !== previousStatus) {
    courier.status = mapped;
    courier.statusHistory.push({
      status: mapped,
      timestamp: new Date(),
      notes: `${source === 'webhook' ? 'Webhook' : 'Sync'}: ${providerStatus}`,
    });
    if (mapped === 'picked' && !courier.pickupDate) courier.pickupDate = new Date();
    if (mapped === 'delivered' && !courier.deliveryDate) courier.deliveryDate = new Date();
  }

  await courier.save();

  if (mapped && mapped !== previousStatus) {
    await mirrorToOrder(courier);
  }
}

/** Courier status → order status, for the transitions the shop cares about. */
const ORDER_STATUS_FOR_COURIER: Partial<Record<CourierStatus, string>> = {
  picked: 'shipped',
  in_transit: 'shipped',
  delivered: 'delivered',
};

/**
 * Reflects the consignment onto the order the customer sees: its tracking
 * number, the carrier, and — for the shipped/delivered milestones — the order
 * status itself, with the same customer notification a manual change fires.
 */
async function mirrorToOrder(courier: any): Promise<void> {
  try {
    const orderId = courier.order?._id ?? courier.order;
    if (!orderId) return;

    const order = await Order.findById(orderId);
    if (!order) return;

    const previousStatus = order.orderStatus;
    let changed = false;

    const tracking = courier.trackingNumber || courier.trackingCode || courier.consignmentId;
    if (tracking && order.trackingNumber !== tracking) {
      order.trackingNumber = tracking;
      changed = true;
    }
    if (courier.courierPartner && tracking) {
      order.courierInfo = {
        courierName: courier.courierPartner,
        trackingId: tracking,
        courierPhone: order.courierInfo?.courierPhone,
      };
      changed = true;
    }

    const nextOrderStatus = ORDER_STATUS_FOR_COURIER[courier.status as CourierStatus];
    // Never walk a cancelled order forward, and never re-announce a milestone
    // the order has already passed.
    const advanceable =
      nextOrderStatus &&
      nextOrderStatus !== previousStatus &&
      !['cancelled', 'delivered'].includes(previousStatus);

    if (advanceable) {
      order.orderStatus = nextOrderStatus as typeof order.orderStatus;
      if (nextOrderStatus === 'delivered' && !order.deliveredAt) {
        order.deliveredAt = new Date();
      }
      changed = true;
    }

    if (!changed) return;
    await order.save();

    if (advanceable) {
      await notifyCustomerOrderStatusChanged({
        userId: order.customer ? String(order.customer) : null,
        orderId: order._id.toString(),
        orderNumber: order.orderNumber,
        status: order.orderStatus,
        previousStatus,
      });
    }
  } catch (error) {
    // The consignment is already recorded; a mirroring failure must not undo it.
    logger.error('Failed to mirror courier status onto order', {
      courierId: courier.courierId,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}
