import { auth } from '@/lib/auth';
import { ensureCourierForOrder } from '@/lib/courier/auto-create';
import { autoDispatchOrderCourier } from '@/lib/courier/dispatch';
import { syncOrderRewards } from '@/lib/deals/settlement';
import AuditLog from '@/lib/models/AuditLog';
import Order from '@/lib/models/Order';
import connectDB from '@/lib/mongodb';
import { notifyCustomerOrderStatusChanged } from '@/lib/notifications/events';

import { NextRequest, NextResponse } from 'next/server';

export async function PUT(
  request: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth();
    if (!session || !['admin', 'manager', 'staff'].includes(session.user?.role)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();
    
    const { status, notes } = await request.json();
    const { id } = await context.params;
    const oldOrder = await Order.findById(id);
    
    if (!oldOrder) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    const updatedOrder = await Order.findByIdAndUpdate(
      id,
      { 
        orderStatus: status,
        ...(notes && { notes }),
        ...(status === 'delivered' && { deliveredAt: new Date() })
      },
      { new: true }
    ).populate('customer').populate('items.product');


    // Settle, release or reverse the delivered-settled rewards this status
    // change implies. Idempotent, so a repeated update grants nothing twice.
    if (updatedOrder) {
      await syncOrderRewards({
        _id: updatedOrder._id,
        customer: updatedOrder.customer?._id ?? updatedOrder.customer,
        orderStatus: updatedOrder.orderStatus,
        paymentStatus: updatedOrder.paymentStatus,
      });

      try {
        await notifyCustomerOrderStatusChanged({
          userId: updatedOrder.customer?._id
            ? String(updatedOrder.customer._id)
            : updatedOrder.customer
              ? String(updatedOrder.customer)
              : null,
          orderId: updatedOrder._id.toString(),
          orderNumber: updatedOrder.orderNumber,
          status: updatedOrder.orderStatus,
          previousStatus: oldOrder.orderStatus,
        });
      } catch (notificationError) {
        console.error('Failed to enqueue customer order status notification:', notificationError);
      }
    }

    /*
     * Confirming an order implies a parcel. Create the record, then push it to
     * the carrier if the admin opted into automatic dispatch.
     *
     * Both steps are non-throwing by contract: a courier problem must never
     * roll back the order status change that triggered it.
     */
    if (status === 'confirmed' && oldOrder.orderStatus !== 'confirmed') {
      await ensureCourierForOrder(updatedOrder, session.user.id, {
        source: 'order-status-route',
      });

      // Idempotent on `consignmentId`, so a repeated confirmation cannot
      // double-book a parcel that is already with the carrier.
      await autoDispatchOrderCourier(id);
    }

    // Log audit
    await AuditLog.create({
      user: session.user.id,
      action: 'UPDATE',
      resource: 'Order',
      resourceId: id,
      changes: [
        {
          field: 'orderStatus',
          oldValue: oldOrder.orderStatus,
          newValue: status
        }
      ],
      metadata: { 
        orderNumber: updatedOrder.orderNumber,
        notes: notes || ''
      }
    });

    return NextResponse.json({
      ...updatedOrder,
      courierAutoGenerated: status === 'confirmed' && oldOrder.orderStatus !== 'confirmed'
    });
  } catch (error) {
    console.error('Update order status error:', error);
    return NextResponse.json({ error: 'Failed to update order status' }, { status: 500 });
  }
}