import { auth } from '@/lib/auth';
import { ensureCourierForOrder } from '@/lib/courier/auto-create';
import { autoDispatchOrderCourier } from '@/lib/courier/dispatch';
import { syncOrderRewards } from '@/lib/deals/settlement';
import AuditLog from '@/lib/models/AuditLog';
import Order from '@/lib/models/Order';
import connectDB from '@/lib/mongodb';
import { notifyCustomerOrderStatusChanged } from '@/lib/notifications/events';
import { cleanupCouriersForOrder } from '@/lib/utils/courierCleanup';
import { NextRequest, NextResponse } from 'next/server';

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth();
    if (!session || !['admin', 'manager', 'staff'].includes(session.user?.role)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();
    
    const { id } = await context.params;
    const order = await Order.findById(id)
      .populate('customer', 'firstName lastName email phone')
      .populate('items.product', 'name thumbnailImage');
    
    if (!order) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    return NextResponse.json(order);
  } catch (error) {
    console.error('Get order error:', error);
    return NextResponse.json({ error: 'Failed to fetch order' }, { status: 500 });
  }
}

export async function PATCH(
  request: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth();
    if (!session || !['admin', 'manager', 'staff'].includes(session.user?.role)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();
    
    const { id } = await context.params;
    const updateData = await request.json();
    
    const oldOrder = await Order.findById(id);
    if (!oldOrder) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    // Update order
    const updatedOrder = await Order.findByIdAndUpdate(
      id,
      {
        ...updateData,
        ...(updateData.orderStatus === 'delivered' && { deliveredAt: new Date() })
      },
      { new: true }
    ).populate('customer').populate('items.product');


    // Settle, release or reverse the delivered-settled rewards implied by this
    // update. Idempotent, so repeated PATCHes grant nothing twice.
    if (updatedOrder) {
      await syncOrderRewards({
        _id: updatedOrder._id,
        customer: updatedOrder.customer?._id ?? updatedOrder.customer,
        orderStatus: updatedOrder.orderStatus,
        paymentStatus: updatedOrder.paymentStatus,
      });

      try {
        await notifyCustomerOrderStatusChanged({
          userId: updatedOrder.customer?._id
            ? String(updatedOrder.customer._id)
            : updatedOrder.customer
              ? String(updatedOrder.customer)
              : null,
          orderId: updatedOrder._id.toString(),
          orderNumber: updatedOrder.orderNumber,
          status: updatedOrder.orderStatus,
          previousStatus: oldOrder.orderStatus,
        });
      } catch (notificationError) {
        console.error('Failed to enqueue customer order status notification:', notificationError);
      }
    }

    let courierAutoGenerated = false;
    /*
     * Confirming an order implies a parcel. Create the record, then push it to
     * the carrier if the admin opted into automatic dispatch.
     *
     * Both steps are non-throwing by contract: a courier problem must never
     * roll back the order status change that triggered it.
     */
    if (updateData.orderStatus === 'confirmed' && oldOrder.orderStatus !== 'confirmed') {
      const courierResult = await ensureCourierForOrder(
        updatedOrder,
        session.user.id,
        { source: 'order-patch-route' },
      );
      courierAutoGenerated = courierResult.created;

      // Idempotent on `consignmentId`, so a repeated confirmation cannot
      // double-book a parcel that is already with the carrier.
      await autoDispatchOrderCourier(id);
    }

    // Log audit for significant changes
    const changes = [];
    if (updateData.orderStatus && updateData.orderStatus !== oldOrder.orderStatus) {
      changes.push({
        field: 'orderStatus',
        oldValue: oldOrder.orderStatus,
        newValue: updateData.orderStatus
      });
    }
    if (updateData.paymentStatus && updateData.paymentStatus !== oldOrder.paymentStatus) {
      changes.push({
        field: 'paymentStatus',
        oldValue: oldOrder.paymentStatus,
        newValue: updateData.paymentStatus
      });
    }

    if (changes.length > 0) {
      await AuditLog.create({
        user: session.user.id,
        action: 'UPDATE',
        resource: 'Order',
        resourceId: id,
        changes,
        metadata: { 
          orderNumber: updatedOrder.orderNumber,
          notes: updateData.notes || ''
        }
      });
    }

    return NextResponse.json({
      ...updatedOrder.toObject(),
      courierAutoGenerated
    });
  } catch (error) {
    console.error('Update order error:', error);
    return NextResponse.json({ error: 'Failed to update order' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const session = await auth();
    if (!session || !['admin', 'manager'].includes(session.user?.role)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();
    
    const { id } = await context.params;
    const order = await Order.findById(id);
    
    if (!order) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    // First, cleanup all associated courier records using utility function
    const courierCleanup = await cleanupCouriersForOrder(id);

    // Then delete the order
    await Order.findByIdAndDelete(id);

    // Log audit with courier cleanup information
    await AuditLog.create({
      user: session.user.id,
      action: 'DELETE',
      resource: 'Order',
      resourceId: id,
      changes: [],
      metadata: { 
        orderNumber: order.orderNumber,
        reason: 'Manual deletion via admin panel',
        cascadeDeleted: {
          couriers: {
            count: courierCleanup.deletedCount,
            courierIds: courierCleanup.deletedCourierIds
          }
        }
      }
    });

    return NextResponse.json({ 
      message: courierCleanup.deletedCount > 0 
        ? 'Order and associated courier records deleted successfully'
        : 'Order deleted successfully',
      orderNumber: order.orderNumber,
      deletedCouriers: courierCleanup.deletedCount
    });
  } catch (error) {
    console.error('Delete order error:', error);
    return NextResponse.json({ error: 'Failed to delete order' }, { status: 500 });
  }
}
